ballerina-platform/module-ballerina-os

- build.gradle
- gradle.properties
- system-ballerina/Ballerina.toml
- system-ballerina/build.gradle
- system-native/build.gradle
> Add stdlib dependencies

- .github/workflows/build-master.yml
- README.md
- system-ballerina/build.gradle
> Add readme in system module

- system-ballerina/src/system/process.bal
- system-ballerina/src/system/system.bal
- system-ballerina/src/system/tests/unit-tests/system-test.bal
> Migrate system module to Ballerina latest syntax

- system-native/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Destroy.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Exec.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/ExitCode.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/GetUserHome.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/GetUsername.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Stderr.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Stdin.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Stdout.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/WaitForExit.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/utils/SystemUtils.java
- system-test-utils/src/main/java/org/ballerinalang/stdlib/system/testutils/SystemTestUtils.java
> Migrate jBallerina Runtime APIs

- .github/workflows/pull-request.yml
- system-ballerina/src/system/process.bal
- system-ballerina/src/system/system.bal
> Mark functions as isolated

- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- build.gradle
- system-ballerina/build.gradle
> Update github release flow

- .github/workflows/build-master.yml
- .github/workflows/daily-build.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- build.gradle
- gradle.properties
- system-native/src/main/java/org/ballerinalang/stdlib/system/utils/SystemConstants.java
> Update build and workflow scripts for releasing and publishing

- .github/workflows/build-master.yml
- .github/workflows/daily-build.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- README.md
- system-ballerina/Ballerina.toml
- system-ballerina/build.gradle
- system-native/build.gradle
- system-native/src/main/java/module-info.java
- system-test-utils/build.gradle
- system-test-utils/src/main/java/module-info.java
- system-test-utils/src/main/java/org/ballerinalang/stdlib/system/testutils/SystemTestUtils.java
> Migrate to JDK11

- system-test-utils/src/main/java/module-info.java
- system-test-utils/src/main/java/org/ballerinalang/stdlib/system/testutils/SystemTestUtils.java
> Add function to check OS

- system-native/src/main/java/module-info.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Destroy.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Exec.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/ExitCode.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/GetUserHome.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/GetUsername.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Stderr.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Stdin.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/Stdout.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/WaitForExit.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/utils/SystemConstants.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/utils/SystemUtils.java
- system-test-utils/src/main/java/module-info.java
- system-test-utils/src/main/java/org/ballerinalang/stdlib/system/testutils/SystemTestUtils.java
Refactor ballerina runtime api usages
> Migrate ballerina runtime apis

- gradle.properties
> Bump stdlib dependency versions

- system-native/src/main/java/org/ballerinalang/stdlib/system/utils/SystemConstants.java
> Updated package version constant

- system-ballerina/system.bal
- system-ballerina/tests/unit-tests/system-test.bal
- system-native/build.gradle
- system-native/src/main/java/org/ballerinalang/stdlib/system/nativeimpl/ModuleUtils.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/utils/SystemConstants.java
- system-native/src/main/java/org/ballerinalang/stdlib/system/utils/SystemUtils.java
- system-test-utils/build.gradle
- system-test-utils/src/main/java/org/ballerinalang/stdlib/system/testutils/SystemTestUtils.java
> Remove UUID related APIs

- system-ballerina/init.bal
> Add init method

- gradle.properties
> Bump module version

- os-ballerina/build.gradle
> Update ballerina command to bal
> Update ballerina command

- os-ballerina/init.bal
- os-ballerina/os.bal
- os-ballerina/process.bal
- os-ballerina/tests/os-test.bal
Related Issue: ballerina-platform/ballerina-lang#28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
> Change the name of the `java` langlib module to `jballerina.java`

- os-ballerina/Ballerina.toml
- os-ballerina/Dependencies.toml
- os-ballerina/build.gradle
Fixes ballerina-platform/ballerina-lang#27988
> Add Dependencies.toml

- os-ballerina/build.gradle
> Revert dependency toml file after build

- .github/workflows/build-master.yml
- .github/workflows/pull-request.yml
- os-ballerina/build.gradle
> Enable publishing of code coverage

- os-ballerina/build.gradle
> Avoid running tests twice when publishing

- README.md
- os-ballerina/Package.md
> Rename module to package in Readme.md and Package.md

- build.gradle
- os-ballerina/build.gradle
> Re-order build tasks to enable publishing to central

- os-ballerina/build.gradle
- os-ballerina/tests/os-test.bal
- os-test-utils/src/main/java/org/ballerinalang/stdlib/system/testutils/EnvironmentTestUtils.java
> Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/160
> Check the OS type before test assertion.
- Unit tests 
Yes
> MacOS, Windows
> Fix tests in windows environment

- .github/workflows/build-master.yml
- .github/workflows/pull-request.yml
- os-ballerina/build.gradle
> Remove publishing exec artifacts and archiving test json

- os-ballerina/build.gradle
> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763
> Add extracted bala in the zip artifact

- os-ballerina/build.gradle
> Add -c flag to build command
> Related to ballerina-platform/ballerina-lang#29032
> Add -c flag to build command

- .github/workflows/central-publish.yml
- README.md
- os-ballerina/build.gradle
> Move Ballerina build, test and publish into a single task

- .github/workflows/publish-release.yml
> Fix indentation

- os-ballerina/tests/os-test.bal
- os-native/src/main/java/org/ballerinalang/stdlib/os/nativeimpl/GetUserHome.java
- os-native/src/main/java/org/ballerinalang/stdlib/os/nativeimpl/GetUsername.java
- os-native/src/main/java/org/ballerinalang/stdlib/os/utils/OSUtils.java
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/1292
> Add unit tests and improve test coverage

- os-ballerina/build.gradle
Set flag to enable Jacoco Coverage XML generation. Fixes https://github.com/ballerina-platform/ballerina-lang/issues/30381
> Set flag to enable Jacoco Coverage XML generation

- build-config/checkstyle/build.gradle
- build.gradle
- gradle.properties
- os-ballerina/build.gradle
Standardize build script of Ballerina module
> Apply Gradle Ballerina plugin for Ballerina module build script 

- README.md
- os-ballerina/Module.md
- os-ballerina/Package.md
- os-ballerina/os.bal
> Improve API Docs and add Package.MD file

- gradle.properties
> Bump ballerina gradle plugin

- os-ballerina/build.gradle
Remove overriding testCoverageParam and use the value from the gradle plugin.
> Remove overriding testCoverageParam

- gradle.properties
> Bump plugin version to 0.8.3

- .github/workflows/build-timestamped-master.yml
- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- build.gradle
- os-ballerina/Package.md
Related to ballerina-platform/ballerina-release#547 and ballerina-platform/ballerina-standard-library#1462
> Update Package.md and workflow config

- .github/workflows/publish-release.yml
- .github/workflows/trivy-scan.yml
- README.md
- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
https://github.com/ballerina-platform/ballerina-standard-library/issues/1849
> Integrate Trivy vulnerability scanner

- .github/workflows/build-timestamped-master.yml
- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
https://github.com/ballerina-platform/ballerina-standard-library/issues/2362
> Skip master build for .md file changes

- ballerina/Ballerina.toml
- docs/spec/spec.md
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2339
> Add os module specification

- ballerina/Dependencies.toml
- ballerina/os.bal
- ballerina/tests/os-test.bal
- native/src/main/java/io/ballerina/stdlib/os/nativeimpl/GetUserHome.java
- native/src/main/java/io/ballerina/stdlib/os/nativeimpl/GetUsername.java
- native/src/main/java/io/ballerina/stdlib/os/utils/OSUtils.java
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2341
> Improve code quality

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
$subject 
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/2478
> Update version for distribution slbeta6

- docs/proposals/environment-variables.md
Related issues: 
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2630
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2666
> Add proposal for envoronment variable operations

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- gradle.properties
> Update package version to 1.3.0

- ballerina/Ballerina.toml
- gradle.properties
> Update dependencies to the latest timestamp version

- native/src/main/java/io/ballerina/stdlib/os/nativeimpl/SetEnv.java
- native/src/main/java/module-info.java
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/2920
> Fix warning messages in setEnv function

- ballerina/Ballerina.toml
- gradle.properties
> Update Language version to 2201.0.4

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- ballerina/build.gradle
- build-config/resources/Ballerina.toml
- gradle.properties
$subject 
part of https://github.com/ballerina-platform/ballerina-standard-library/issues/3128
> Migrate OS module to ballerina Update 2

- ballerina/Ballerina.toml
- gradle.properties
> Move to latest lang version

- ballerina/Ballerina.toml
- ballerina/build.gradle
> Fix uncommitted file issue in gradle task

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- native/src/main/resources/META-INF/native-image/io.ballerina.stdlib/os-native/reflect-config.json
Fixes : [#3395](https://github.com/ballerina-platform/ballerina-standard-library/issues/3395)
Related to :[#3315](https://github.com/ballerina-platform/ballerina-standard-library/issues/3315)
> Add configs for native-image support

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
> Add type reference support

- .github/workflows/build-with-bal-test-graalvm.yml
- README.md
- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- gradle.properties
$Subject
Part of : https://github.com/ballerina-platform/ballerina-standard-library/issues/4548
> Incoperate native build command change

- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- gradle.properties
> Update dependency version

- .github/workflows/build-timestamped-master.yml
- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trivy-scan.yml
- README.md
- ballerina/Ballerina.toml
- build-config/checkstyle/build.gradle
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
> Migrate to Java 17

- .github/workflows/build-timestamped-master.yml
- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trivy-scan.yml
- .github/workflows/update_specs.yml
- ballerina/Ballerina.toml
- build-config/resources/Ballerina.toml
> Bump workflow actions

- native/src/main/java/io/ballerina/stdlib/os/nativeimpl/SetEnv.java
> Remove disable warnings

- README.md
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
> Fix Oracle JDK download link

- .github/workflows/build-timestamped-master.yml
- .github/workflows/build-with-bal-test-graalvm.yml
- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trivy-scan.yml
> Update workflows to the ballerina-library

- .github/workflows/build-timestamped-master.yml
- .github/workflows/build-with-bal-test-graalvm.yml
- .github/workflows/central-publish.yml
- .github/workflows/publish-release.yml
- .github/workflows/pull-request.yml
- .github/workflows/trivy-scan.yml
- README.md
- ballerina/Ballerina.toml
- ballerina/Dependencies.toml
- build-config/resources/Ballerina.toml
- gradle.properties
- native/build.gradle
- test-utils/build.gradle
- test-utils/src/main/java/io/ballerina/stdlib/os/testutils/OSTestUtils.java
> Migrate to Java 21

- build-config/resources/Ballerina.toml
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
> Update dependency versions for Update 11

- .gitignore
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/build.gradle
- build-config/resources/Ballerina.toml
- build-config/resources/CompilerPlugin.toml
- changelog.md
- compiler-plugin-tests/build.gradle
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/os/compiler/staticcodeanalyzer/ProcessOutputGobbler.java
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/os/compiler/staticcodeanalyzer/StaticCodeAnalyzerTest.java
- compiler-plugin-tests/src/test/resources/static_code_analyzer/ballerina_packages/rule1/Ballerina.toml
- compiler-plugin-tests/src/test/resources/static_code_analyzer/ballerina_packages/rule1/main.bal
- compiler-plugin-tests/src/test/resources/static_code_analyzer/expected_output/rule1.json
- compiler-plugin-tests/src/test/resources/testng.xml
- compiler-plugin/build.gradle
- compiler-plugin/src/main/java/io/ballerina/stdlib/os/compiler/Constants.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/os/compiler/OSCompilerPlugin.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/os/compiler/staticcodeanalyzer/OSCommandInjectionAnalyzer.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/os/compiler/staticcodeanalyzer/OSRule.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/os/compiler/staticcodeanalyzer/OSStaticCodeAnalyzer.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/os/compiler/staticcodeanalyzer/RuleFactory.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/os/compiler/staticcodeanalyzer/RuleImpl.java
- compiler-plugin/src/main/java/module-info.java
- compiler-plugin/src/main/resources/rules.json
- gradle.properties
- settings.gradle
Reverts ballerina-platform/module-ballerina-os#537
> Revert "Revert static code rule change"

- .gitignore
- ballerina/Ballerina.toml
- ballerina/CompilerPlugin.toml
- ballerina/Dependencies.toml
- ballerina/build.gradle
- build-config/resources/Ballerina.toml
- build-config/resources/CompilerPlugin.toml
- changelog.md
- compiler-plugin-tests/build.gradle
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/os/compiler/staticcodeanalyzer/ProcessOutputGobbler.java
- compiler-plugin-tests/src/test/java/io/ballerina/stdlib/os/compiler/staticcodeanalyzer/StaticCodeAnalyzerTest.java
- compiler-plugin-tests/src/test/resources/static_code_analyzer/ballerina_packages/rule1/Ballerina.toml
- compiler-plugin-tests/src/test/resources/static_code_analyzer/ballerina_packages/rule1/main.bal
- compiler-plugin-tests/src/test/resources/static_code_analyzer/expected_output/rule1.json
- compiler-plugin-tests/src/test/resources/testng.xml
- compiler-plugin/build.gradle
- compiler-plugin/src/main/java/io/ballerina/stdlib/os/compiler/Constants.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/os/compiler/OSCompilerPlugin.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/os/compiler/staticcodeanalyzer/OSCommandInjectionAnalyzer.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/os/compiler/staticcodeanalyzer/OSRule.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/os/compiler/staticcodeanalyzer/OSStaticCodeAnalyzer.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/os/compiler/staticcodeanalyzer/RuleFactory.java
- compiler-plugin/src/main/java/io/ballerina/stdlib/os/compiler/staticcodeanalyzer/RuleImpl.java
- compiler-plugin/src/main/java/module-info.java
- compiler-plugin/src/main/resources/rules.json
- gradle.properties
- settings.gradle
> Add scan tool
